mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: rtmp://192.168.20.10:1935/test/Zcam_17_lo.flv
          input_args: -rtmp_live live -fflags +genpts+discardcorrupt -flags low_delay
          roles:
            - detect
            - record
    detect:
      height: 1080
      width: 1920
      fps: 5
    record:
      enabled: true
version: 0.17-0
